CREATE TABLE IF NOT EXISTS currency
(
	id SERIAL PRIMARY KEY,
	crypto CHARACTER VARYING(30),
	usd FLOAT
);

CREATE TABLE IF NOT EXISTS users
(
	id SERIAL PRIMARY KEY,
	email CHARACTER VARYING(30),
	userId BIGINT
);